### ISSUE TITLE
Change slice types to interface when not the same? - panic: reflect.AppendSlice: interface {} != string

### ISSUE THREAD

**Issue by MichaelS11** [mattn/anko#76]
Greetings,

Do you think it would be alright to add some more code to vm.go to check if slices/array as the same type before appending them? Change them to interface automatically when they are not?

If it is alright to do the automatic conversion to interface, I can see about working on a PR.

```Go
package main

import (
	"fmt"
	"reflect"

	"github.com/mattn/anko/builtins"
	"github.com/mattn/anko/vm"
)

func main() {
	var value reflect.Value

	vmEnv := vm.NewEnv()
	core.LoadAllBuiltins(vmEnv)

	input := []string{"one", "two"}

	err := vmEnv.Define("input", input)
	if err != nil {
		fmt.Printf("Define error: %v", err)
		return
	}

	script := `
output = []

output += input
`

	_, err = vmEnv.Execute(script)
	if err != nil {
		fmt.Printf("Get error: %v", err)
		return
	}

	value, err = vmEnv.Get("output")
	if err != nil {
		fmt.Printf("Get error: %v", err)
		return
	}

	fmt.Println(value)
}

```

```
panic: reflect.AppendSlice: interface {} != string

goroutine 1 [running]:
reflect.typesMustMatch(0x8153b4, 0x13, 0x9b7160, 0x7a4d20, 0x9b7160, 0x78d720)
	C:/app/Go/src/reflect/value.go:1790 +0x19c
reflect.AppendSlice(0x7876a0, 0xc0420a8e60, 0x97, 0x788860, 0xc0420a8d40, 0x97, 0x0, 0x0, 0x0)
	C:/app/Go/src/reflect/value.go:1844 +0x123
vendor/github.com/mattn/anko/vm.invokeExpr(0x9b18a0, 0xc04200c400, 0xc042010500, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/mattn/anko/vm/vm.go:1207 +0x230d
vendor/github.com/mattn/anko/vm.invokeExpr(0x9b1860, 0xc04200c3c0, 0xc042010500, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/mattn/anko/vm/vm.go:1121 +0x6b97
vendor/github.com/mattn/anko/vm.RunSingleStmt(0x9b1b20, 0xc0420a8e20, 0xc042010500, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/mattn/anko/vm/vm.go:130 +0x476a
vendor/github.com/mattn/anko/vm.Run(0xc0420a8e40, 0x2, 0x2, 0xc042010500, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/mattn/anko/vm/vm.go:95 +0x286
vendor/github.com/mattn/anko/vm.(*Env).Execute(0xc042010500, 0x81a160, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/username/Documents/Eclipse/src/vendor/github.com/mattn/anko/vm/env.go:257 +0x14f
main.main()
	C:/Users/username/Documents/Eclipse/src/test/main.go:32 +0x2ce
```

vm.go code in question:
```Go
			if (lhsV.Kind() == reflect.Array || lhsV.Kind() == reflect.Slice) && (rhsV.Kind() != reflect.Array && rhsV.Kind() != reflect.Slice) {
				return reflect.Append(lhsV, rhsV), nil
			}
			if (lhsV.Kind() == reflect.Array || lhsV.Kind() == reflect.Slice) && (rhsV.Kind() == reflect.Array || rhsV.Kind() == reflect.Slice) {
				return reflect.AppendSlice(lhsV, rhsV), nil
			}
```

Best regards,

Michael

**Comment by mattn** [comment]
If you will make PR, I'm happy.

**Comment by MichaelS11** [comment]
Will be getting to this, been working on getting some of the tests updated and etc.
